baseURL: 'https://www.marcoguzzo.net/'
title: Marco Guzzo
author: Marco Guzzo
languageCode: en-us
pygmentsCodeFences: true
enableRobotsTXT: true
theme: hugo-flex
publishDir: public

permalinks:
  posts: '/:filename/'
  pages: '/:filename/'

params:
  color: tomato # Colors: https://www.w3schools.com/cssref/css_colors.asp
  width: 42rem
  description: Marco Guzzo's Homepage and Projects
  footer: >-
    <a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-sa/4.0/88x31.png" /></a><br />This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/">Creative Commons Attribution-ShareAlike 4.0 International License</a>.
  rss: >-
    To subscribe to this RSS feed, copy the address in the address bar and paste
    it into your favorite feed reader.
  divider: '\2015\2015' # Set to false to remove divider below posts on homepage
  schema: false
  opengraph: false
  twittercards: false
  summaries: false
  css:
    - css/custom.css

taxonomies:
  category: "categories"
  tag: "tags"

  # utterances:
  #   repo:               # Set to Utterances repo URL to add Utterances comments
  #   issueterm: pathname
  #   theme: github-light
  # netlify:
  #   honeypot: false     # Set to true to add honeypot field in contact form
  #   recaptcha: false    # Set to true to add recaptcha challenge in contact form
  # css:                # Uncomment to add custom CSS from a list of files
  #   - css/foo.css
  #   - bar.css
  # js:                 # Uncomment to add custom JS from a list of files
  #   - js/foo.js
  #   - bar.js



menu:
  nav:
    - name: âš™ï¸  Projects
      url: projects/
      weight: 1
    - name: ğŸ“°  Blog
      url: posts/
      weight: 2
    - name: âœ‰ï¸  Contact
      url: contact/
      weight: 3
    - name: ğŸ“¡ RSS
      url: index.xml
      weight: 4
